### PR TITLE
support mira.frame color attribute

### PR DESCRIPTION
**Pull request by fde31**
Enhancement to make the color attribute of mira.frame set the bg of our Pixi Canvas and the surrounding background. Additionally the bg of the frame tabs is coloured accordingly, too.

I used a feature branch though as we don't take the bg color of the containing patcher into consideration and per default mira.frame has a opacity applied that isn't 1. Therefore the color in the browser appears different than the one in Max. Maybe no issue as this replicates the behaviour of Mira App? However, guess we might wanna discuss/vote and decide whether this is 'good enough' for now or if we should also tackle the more complex patcher bg color mixing into consideration for a potentially to be released 'fix'.

### CODE REVIEW

**Comment by fde31** [comment]
Example of new background color usage:

screen shot 2017-01-04 at 19 31 49

Showcasing difference in color value due to opacity/mixing with patcher bg

screen shot 2017-01-04 at 19 32 12

**Comment by fde31** [comment]
I made a PR on xebra.js in order to support the color and locked states of patchers and the color attr of mira.frame here:

Once this is merged this PR calculates the bg color of the shown tabs/frames according to the mira.frame color attr, the patcher locked state (if mira.frame color has a alpha different than 1) and the according bgcolor of it. 

Here is a quick vid showcasing the behaviour:
https://drive.google.com/file/d/0B4q0ttVZWeNBSm5oMWxxd1dVck0/view?usp=sharing

**Comment by benbrackenc74** [comment]
I don't really have a handle on a good solution here. I guess you can use panels as well...I guess if I was using it, I would want the frame rect to be separately controlled from the tab and the rect outside of the frame. That being said, I don't feel very passionate about it.

**Comment by fde31** [comment]
OK. I added a couple of features on this branch

- Save & Restore for Settings (GlobalViewMode is now also stored properly in the SettingsStore)
- Three Color Modes for the background Tab/Frame:

1. Darken (default) - tab/bg in the color of the mira.frame darkened by 2%
2. Lighten - tab/bg in the color of the mira.frame brightened by 2%
3. Fixed Color - tab/bg in a fixed color, which can be set with a color picker

I guess with these we might have enough options for people to customize their looks on the client with Settings that get restored between launches in the same browser?!

**Comment by fde31** [comment]
you wanna take a look again @benbrackenc74?

**Comment by benbrackenc74** [comment]
@fde31 the hex/rgb input in the colorpicker in FF is somehow cut off. Chrome is fine: 
screen shot 2017-01-09 at 1 38 11 pm

**Comment by fde31** [comment]
yeah. our custom Input and Select styling was clashing/overriding. I namespaced these into components and it should be fine now.

**Comment by fde31** [comment]
@benbrackenc74 should we merge?

**Pull request merged**
