### PR TITLE
See #9 --- should be handling pointer family of events only, which is…

### PR DESCRIPTION
**Pull request by starakaj**
… possible with the new pixi code

### CODE REVIEW

**Comment by fde31** [comment]
looking into it....

**Comment by fde31** [comment]
seems good now! Finally. Was there a change left for us to merge wrt Pixi etc? Or just an oversight after our last fix?

**Comment by fde31** [comment]
@starakaj just wanna comment on my question? Otherwise I'd say: merge away!

**Comment by starakaj** [comment]
I think we were waiting for some small bugfix on the pixi end? Really I can't remember though---probably we got distracted by something more pressing.

**Pull request merged**
